<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" />
    <PackageReference Include="Microsoft.SemanticKernel.Core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IronLogic.Domain\IronLogic.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mappers\" />
    <Folder Include="Services\" />
    <Folder Include="Validation\" />
    <Folder Include="Validators\" />
  </ItemGroup>

  <PropertyGroup>
   
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>