import {
  ApplicationConfig,
  importProvidersFrom,
  provideZonelessChangeDetection,
} from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient } from '@angular/common/http';
import { routes } from './app.routes';

import {
  Activity,
  ArrowUpRight,
  Bell,
  Banknote,
  Bell,
  Calendar,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheckBig,
  CreditCard,
  Dumbbell,
  Edit3,
  Eye,
  Filter,
  Gauge,
  Globe,
  GripVertical,
  Info,
  Layers,
  LayoutDashboard,
  LucideAngularModule,
  Lock,
  Mail,
  PanelLeft,
  Pencil,
  RefreshCw,
  Search,
  SlidersHorizontal,
  Settings,
  Star,
  ShieldCheck,
  ShieldOff,
  Trash2,
  TrendingUp,
  Upload,
  Users,
  UserPlus,
  Zap,
  Weight,
  Wrench,
  X,
  AlertTriangle,
  MoreHorizontal,
  FileSpreadsheet,
  FileText,
} from 'lucide-angular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZonelessChangeDetection(),
    provideRouter(routes),
    provideHttpClient(),
    importProvidersFrom(
      LucideAngularModule.pick({
        Activity,
        AlertTriangle,
        ArrowUpRight,
        Bell,
        Banknote,
        Bell,
        Calendar,
        Check,
        ChevronDown,
        ChevronLeft,
        ChevronRight,
        CircleCheckBig,
        CreditCard,
        Dumbbell,
        Edit3,
        Eye,
        FileSpreadsheet,
        FileText,
        Filter,
        Gauge,
        Globe,
        GripVertical,
        Info,
        LayoutDashboard,
        Layers,
        Lock,
        Mail,
        MoreHorizontal,
        PanelLeft,
        Pencil,
        RefreshCw,
        Search,
        Settings,
        ShieldCheck,
        ShieldOff,
        SlidersHorizontal,
        Star,
        Trash2,
        TrendingUp,
        Upload,
        Users,
        UserPlus,
        Weight,
        Wrench,
        X,
        Zap,
      }),
    ),
  ],
};
