<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="CsvHelper" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.SemanticKernel" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IronLogic.Domain\IronLogic.Domain.csproj" />
    <ProjectReference Include="..\IronLogic.Application\IronLogic.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ExternalServices\" />
  </ItemGroup>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>